Vagrant.configure("2") do |config|

  config.vm.define "web01" do |web01|
    web01.vm.box = "spox/ubuntu-arm"
    web01.vm.network "private_network", ip: "192.168.40.11"
    web01.vm.provider "vmware_desktop" do |vmware|
      vmware.memory = "1024"
      vmware.cpus = 2
   end
   web01.vm.provision "shell", inline: <<-SHELL
      apt update
      apt install apache2 wget unzip -y
      systemctl stop firewalld
      systemctl disable firewalld 
      systemctl start apache2
      systemctl enable apache2
      cd /tmp/
      wget https://www.tooplate.com/zip-templates/2132_clean_work.zip
      unzip -o 2132_clean_work.zip
      cp -r 2132_clean_work/* /var/www/html/
      systemctl restart apache2
   SHELL
  end



  config.vm.define "db01" do |db01|
    db01.vm.box = "jacobw/fedora35-arm64"
    db01.vm.network "private_network", ip: "192.168.40.12"
    db01.vm.provider "vmware_desktop" do |vmware|
      vmware.memory = "1024"
      vmware.cpus = 2
  end
  db01.vm.provision "shell", inline: <<-SHELL
  yum install mariadb-server -y
   
  systemctl start mariadb
  systemctl enable mariadb

  mysql -u root -e 'CREATE DATABASE wordpress;'
  mysql -u root -e 'GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER ON wordpress.* TO wordpress@localhost IDENTIFIED BY "admin";'
  mysql -u root -e 'FLUSH PRIVILEGES;'
  SHELL
 end
end
