  Vagrant.configure("2") do |config| 
    config.vm.box = "jacobw/fedora35-arm64" 
    config.vm.network "private_network", ip: "192.168.33.10"
    config.vm.network "public_network"
    config.vm.provider "vmware_desktop" do |vmware|
      vmware.gui = true
      vmware.memory = "1024"
      vmware.allowlist_verified = true
    end
  end
